name: Facebook Category Scraper

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  scrape-facebook:
    runs-on:  ubuntu-22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright textblob supabase python-dotenv

      - name: Install Playwright browsers
        run: |
          playwright install firefox
          playwright install-deps firefox

      - name: Download TextBlob Corpora
        run: python -m textblob.download_corpora

      - name: Run Facebook Scraper
        run: python facebook_category_scraper.py
        env:
          FACEBOOK_EMAIL: ${{ secrets.FACEBOOK_EMAIL }}
          FACEBOOK_PASSWORD: ${{ secrets.FACEBOOK_PASSWORD }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        timeout-minutes: 60

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: facebook-results
          path: |
            *.json
            *.log
          retention-days: 7